services:
  academico-login:
    image: ${ACADEMICO_LOGIN_IMAGE}
    container_name: academico-login
    restart: always
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - .env
    environment:
      - NODE_ENV=production
   